import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Super Filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="/">Super Filmes!</a>
        </h1>
        <h2>Sobre o sistema</h2>
        <p>Sistema criado durante estudo inicial do Next Js</p>

        <footer>
          <h3>Criado por: {author}</h3>
        </footer>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      author: 'Jackson Souza'
    }
  }
}